//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF354CA3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_ID { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<int> category_ID { get; set; }
        public Nullable<int> supplier_ID { get; set; }
    
        public virtual category category { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
